=== Giveth/DeVouch/org-config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Organization Configuration",
  "description": "Schema for the organization configuration file.",
  "type": "object",

  "properties": {
    "$schema": {
      "description": "The schema version.",
      "type": "string"
    },
    "name": {
      "description": "The name of the organization.",
      "type": "string"
    },
    "schemaId": {
      "description": "The UID for the attestation schema.",
      "type": "string",
      "pattern": "^0x[A-Fa-f0-9]{64}$"
    },
    "authorizedAttestor": {
      "description": "The address of the authorized attestor.",
      "type": "string",
      "pattern": "^0x[A-Fa-f0-9]{40}$"
    },

    "network": {
      "description": "The network for the organization.",
      "type": "string",
      "enum": ["eth-sepolia", "optimism-mainnet"]
    },

    "color": {
      "description": "The organisaiton color in UI.",
      "type": "string",
      "pattern": "^#[A-Fa-f0-9]{6}$"
    },
    "startBlock": {
      "description": "The block number at which the organization was created.",
      "type": "integer"
    }
  },
  "required": ["name", "schemaId", "authorizedAttestor", "network"],
  "additionalProperties": false
}

=== Giveth/DeVouch/org-config.json
{
  "$schema": "./org-config.schema.json",

  "name": "Optimism Super Delegate",
  "schemaId": "0xe4a196f8ea37d5f9699b095594e44b465b2703eff0615cf9766060786eef517b",
  "authorizedAttestor": "0x93E79499b00a2fdAAC38e6005B0ad8E88b177346",

  "network": "optimism-mainnet",

  "color": "#ff0420",
  "startBlock": 
  121313963
}
